AllCops:
  Exclude:
    - '.brew/**'
    - '.bundle/**'
    - '.cache/**'
    - '.idea/**'
    - '.rbenv/**'
    - '.tmp/**'
    - 'backup/**'

inherit_from:
  - .rubocop_todo.yml

Metrics/AbcSize:
  Max: 280
Metrics/BlockLength:
  Max: 106
Metrics/BlockNesting:
  Max: 5
Metrics/ClassLength:
  Max: 800
Metrics/CyclomaticComplexity:
  Max: 80
Metrics/ParameterLists:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 90
Metrics/MethodLength:
  Max: 260
Metrics/ModuleLength:
  Max: 500

Naming/MethodParameterName:
  MinNameLength: 1

Naming/PredicateName:
  AllowedMethods:
    - is_a?
    - is_32_bit?
    - is_64_bit?

Style/BlockDelimiters:
  BracesRequiredMethods:
    - "sig"
