#!/bin/bash

PROJECT_DIR="$(dirname "${0%.*}")"; export PROJECT_DIR
PATH="${PROJECT_DIR}/bin:${PATH}"; export PATH

export RUBYMINE_PROPERTIES='/Volumes/USB-2TB/Shared/JetBrains/config/RubyMine/.properties'
export RUBYMINE_VM_OPTIONS='/Volumes/USB-2TB/Shared/JetBrains/config/RubyMine/.vmoptions'

/Applications/RubyMine.app/Contents/MacOS/rubymine "${PROJECT_DIR}"
